name: Usman Zubair
description: There is no knowledge that is not power

plugins: [
  jekyll-feed,
  jekyll-sitemap,
  jekyll-seo-tag,
  jekyll-paginate,
]

paginate: 3
paginate_path: "/blog/page/:num/"

markdown: kramdown
kramdown:
 input: GFM
highlighter: rouge

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude: [
  'README.md', 
  'Gemfile.lock', 
  'Gemfile', 
  'Rakefile', 
  'vendor'
]
