name: Usman Zubair
description: There is no knowledge that is not power

author: Usman Zubair
organization: personal
location: Ontario, Canada
social:
  github: uzubair

timezone: America/Toronto

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  math_engine: mathjax

sass:
  style: compressed

paginate: 3
paginate_path: "/blog/page/:num/"

plugins: [
  jekyll-feed,
  jekyll-sitemap,
  jekyll-seo-tag,
  jekyll-paginate,
  rouge
]

exclude: [
  'README.md', 
  'Gemfile.lock', 
  'Gemfile', 
  'Rakefile', 
  'vendor'
]
